// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_WebAPI.Models
{
    public partial class ApiUser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public byte[] RefreshToken { get; set; }
    }

    public partial class ApiUserDTO
    {
        public string UserName { get; set; }
        public string Password{ get; set; }

    }
}